/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package PZN_06KotlinUnitTest

import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Test


class AppTest {
    @Test
    fun appHasAGreeting() {
        println("ini test")
        val classUnderTest = App()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
